CREATE TABLE `libros` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `autor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `titulo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `traductor` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ciudad` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `anio_edicion` int(11) DEFAULT NULL,
  `edicion` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `primera_edicion` int(11) DEFAULT NULL,
  `editorial` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tema_id` int(10) unsigned DEFAULT NULL,
  `tipo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `topografia` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paginas` int(11) DEFAULT NULL,
  `tomos` int(11) DEFAULT NULL,
  `idioma` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `observaciones` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `baja` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `libros_autor_index` (`autor`),
  KEY `libros_titulo_index` (`titulo`),
  KEY `libros_tema_id_foreign` (`tema_id`),
  CONSTRAINT `libros_tema_id_foreign` FOREIGN KEY (`tema_id`) REFERENCES `temas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3797 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
